export type PageContext = {
  id: string
}

export type Reference = {
  target: {
    __typename: string
    body: string
    parent: SimpleFileNode
  }
  targetAnchor?: string
  refWord: string
  referrer: {
    parent: SimpleFileNode
  }
  contextLine: string
  label?: string
}

export type SimpleFileNode = {
  id: string
  fields: {
    title: string
    slug: string
  }
}

export type TopicFlie = {
  id: string
  fields: {
    slug: string
    title: string
  }
  childMdx: {
    body: string
    inboundReferences: Reference[]
    outboundReferences: Reference[]
    frontmatter: {
      title: string
    }
    tableOfContents: TableOfContents
  }
}

export type WikiLinkLabelTemplateFn = (data: { refWord: string; title: string }) => string

/**
 * Table of content item generated by remark
 */
export type TOCItem = {
  items?: TOCItem[]
  title: string
  url: string
}

export type TableOfContents = TOCItem
